// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message_body': string;
  'message_text': string;
}
export const cssExports: CssExports;
export default cssExports;
