//Constants:

export const CREATE_MESSAGE = "MESSAGE/CREATE_MESSAGE";
export const ADD_CURRENT_USER = "USER/ADD_CURRENT_USER";
export const TOGGLE_CHAT_VISIBILITY = "TOGGLE_CHAT_VISIBILITY";
export const CREATE_ISSUE = "CREATE_ISSUE";
export const CREATE_CARDS = "CREATE_CARDS";
export const EDIT_TITLE = "EDIT_TITLE";
export const EDIT_CARD_TITLE = "EDIT_CARD_TITLE";
export const CREATE_RESULT = "CREATE_RESULT";
export const SET_USERSLIST = "SET_USERSLIST";
export const UPDATE_USERSLIST = "UPDATE_USERSLIST";
export const SET_CARDSLIST = "SET_CARDSLIST";
export const SET_ISSUESLIST = "SET_ISSUESLIST";
export const SET_ACTIVE_ISSUE = "SET_ACTIVE_ISSUE";
export const ADD_VOTE = "ADD_VOTE";
