// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'member': string;
  'member_avatar': string;
  'member_block_btn': string;
  'member_name': string;
  'member_position': string;
}
export const cssExports: CssExports;
export default cssExports;
