// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form_input': string;
  'form_submit_btn': string;
}
export const cssExports: CssExports;
export default cssExports;
